### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-switzerland#172]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate (alphabetically)
- [x] l10n_ch (removing) @yvaucher #173 
- [x] l10n_ch_bank @yvaucher #184 
- [x] l10n_ch_base_bank @yvaucher #179 
- [ ] l10n_ch_credit_control_payment_slip_report
- [x] l10n_ch_dta @BT-mtallon #212 
- [ ] l10n_ch_dta_base_transaction_id
- [x] l10n_ch_hr_payroll @open-net-sarl 
- [x] l10n_ch_import_cresus @lbeopennet  #253 
- [ ] l10n_ch_lsv_dd
- [x] l10n_ch_payment_slip @yvaucher #176
- [ ] ~~l10n_ch_payment_slip_account_statement_base_completion~~ this link module shouldn't be necessary anymore
- [ ] l10n_ch_payment_slip_base_transaction_id
- [ ] l10n_ch_payment_slip_layouts @philhug #291
- [x] ~~l10n_ch_payment_slip_voucher~~ deprecated #251 
- [ ] l10n_ch_scan_bvr @BT-aestebanez #272
- [x] ~~l10n_ch_sepa~~ replaced by l10n_ch_pain_base and l10n_ch_pain_credit_transfert
- [x] l10n_ch_states @yvaucher #174 
- [x] l10n_ch_zip @yvaucher #175
  - [x] base_location (dependency) OCA/partner-contact#187

**Comment by yvaucher** [comment]
Let me a message in comments if you need me to update the list of this issue

**Comment by vrenaville** [comment]
@yvaucher could you please add me for l10n_ch_dta ?

**Comment by yvaucher** [comment]
@vrenaville done

**Comment by treviser** [comment]
Count me in for translations of the official swiss terms (accounts, taxes, payroll etc.) in english, french, german and italian. I'm not a developer, but I can edit po and xml files.

**Comment by BT-astauder** [comment]
@yvaucher Could you please add brain-tec for l10n_ch_sepa ?

**Comment by yvaucher** [comment]
@BT-astauder What are your plan about l10n_ch_sepa? It would be great if we could join the common effort done in OCA banking addons

**Comment by fclementic2c** [comment]
@BT-astauder Since the payment order does not exist anymore we need to build a base module for electronic payment (DTA, SEPA CH, SEPA...)

**Comment by yvaucher** [comment]
@treviser Seems we just fixed transifex

For translation you can have a look there:
https://www.transifex.com/oca/OCA-l10n-switzerland-9-0

**Comment by treviser** [comment]
I looked it up, but the resource is empty, nothing to translate?

**Comment by yvaucher** [comment]
Indeed. I assume it only load terms from installable modules, and for now there is only l10n_ch_zip which has been ported

**Comment by treviser** [comment]
@yvaucher Please let us know when you are ready.

**Comment by BT-astauder** [comment]
@vrenaville For us l10n_ch_dta has priority over the sepa module (if this is still needed). Have you already started porting it? We will create a dta for 9.0, but similar to account_sepa. Unfortunately account_sepa is under the Enterprise Licence, so we cannot share the new module here. Any suggestions how to deal with this problem?

**Comment by treviser** [comment]
The Transifex resource is still empty...

On 09.12.2015 19:36, Yannick Vaucher wrote:

> @treviser https://github.com/treviser Seems we just fixed transifex
> 
> For translation you can have a look there:
> https://www.transifex.com/oca/OCA-l10n-switzerland-9-0
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/l10n-switzerland/issues/172#issuecomment-163351746.

## 

twanda AG
Ermin Trevisan
Artherstrasse 19
CH-6318 Walchwil
T    +41 41 758 1515
M    +41 79 208 7373
E    trevi@twanda.com
www.twanda.ch
www.twanda.ch/page/restaurant

**Comment by yvaucher** [comment]
@BT-astauder we definitely need to have a community version of DTA. We haven't started porting it. For now I have focused on porting BVR and V11 imports, which should be ready now. Feel free to test them.

This is a issue of the new Odoo license model, some key features will have to be done twice.

However, you might want to check if the base for making that module is not already in community, in such case it can be compatible for both the Enterprise version AND the Community version as it won't depend on any Enterprise module.

**Comment by yvaucher** [comment]
@treviser sorry nothing new has been merged yet, I had to fixe few issues in payment slip PR. It is in review process, still.

**Comment by treviser** [comment]
let me know when you are ready :-)

On 19.01.2016 16:26, Yannick Vaucher wrote:

> @treviser https://github.com/treviser sorry nothing new has been
> merged yet, I had to fixes few issues in payment slip PR. It is in
> review process, still.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/l10n-switzerland/issues/172#issuecomment-172887696.

## 

twanda AG
Ermin Trevisan
Artherstrasse 19
CH-6318 Walchwil
T    +41 41 758 1515
M    +41 79 208 7373
E    trevi@twanda.com
www.twanda.ch
www.twanda.ch/page/restaurant

**Comment by BT-astauder** [comment]
@yvaucher We thought to take the structure for the l10n_ch_dta from account_sepa. But for generating the DTA itself, the code from OCA would be nice. But as far as I know it's impossible to mix code from both licences. So we have to decide for one part and develop the other part again in a clean room development. Strange, or do you have another idea?

**Comment by BT-astauder** [comment]
Hello @vrenaville

We have a working DTA for 9.0. For the implementation we tried to follow https://docs.google.com/document/d/1FfaitydiW5uFjyIwtMT9fVbScwBefCATmoM2x7HNVbk/edit

You can find the WIP in #212 This is ready for a code review.

**Comment by yvaucher** [comment]
@BT-astauder Sadly you are right about the clean room development.

This is needed to respect the license of contributors who wants their code to remain Open Source. What will happens is that enterprise features like sepa will most likely be still have a lot of support in OCA thus Community version of Odoo will still have it's sepa module developed by the community.

**Comment by yvaucher** [comment]
@treviser Transifex seems now ready for translators to get involved
https://www.transifex.com/oca/OCA-l10n-switzerland-9-0/

**Comment by yvaucher** [comment]
@BT-astauder I remove you from l10n_ch_sepa portage as we @alexis-via did it connecting it with the OCA iso20022 modules of bank-payment

**Comment by BT-astauder** [comment]
@yvaucher ok, thanks to @alexis-via for your work!

**Comment by ghost** [comment]
I did `l10n_ch_import cresus` so it should be ticked off.

**Comment by yvaucher** [comment]
Updated

**Comment by yvaucher** [comment]
Added https://github.com/OCA/l10n-switzerland/pull/272

**Comment by davidwul** [comment]
Why the module l10n_ch_account_statement_base_import is not marked to migrate? I just tried it, it seems I can import bank statement from ubs, with no modification. This module would rather belong to OCA/bank-statement-import? But I think it makes sense to have it in the CH localization.

**Comment by philhug** [comment]
please add #291

**Comment by BT-cserra** [comment]
Hello @yvaucher. Can you please add the module l10n_ch_lsv_dd to the README.md file? Thank you.

**Comment by yvaucher** [comment]
I added it to the list here. The main README.rst is updated by a bot.

**Comment by BT-cserra** [comment]
Thanks @yvaucher.

**Comment by bodi000** [comment]
Hello,
I would like to use the module **l10n_ch_payment_slip_account_statement_base_completion**. I see it unported, therefore I would like to know if any effort has been already done for this migration, so I will not duplicate the work...

It is not very clear to me what are the plans for its dependency **account_statement_base_completion**: (will it be ported, other module will do the job, else?).

Could anyone please give some insight ?

Thank you in advance
B

**Comment by yvaucher** [comment]
@bodi000 AFAIK There is currently noone working on `l10n_ch_payment_slip_account_statement_base_completion` migration to version 9.0.

For `account_statement_base_completion` you have that PR which removed it in https://github.com/OCA/account-reconcile/pull/137

It moved the feature in `account_statement_base_import`.

AFAIK current version 9.0 should be compatible with the new module without the need of an additional one using the [`base_transaction_id`](https://github.com/OCA/account-reconcile/tree/9.0/base_transaction_id) module.

If you look at `l10n_ch_payment_slip` readme:

> This module also adds transaction_ref field on entries in order to manage reconciliation in multi payment
> context (unique reference needed on account.move.line). Many BVR can now be printed from on invoice > for each payment terms.

`transaction_ref` defined with `base_transaction_id` module is used for the reconciliation.

So yes a lot of thing changed but your needs should be covered with the modules in https://github.com/OCA/account-reconcile (side note the repo `account-reconcile` was named `bank-statement-reconcile` in the past you might see some mention of it but github will redirect you on the right one anyway)
