### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-switzerland#271]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] l10n_ch_bank #288
- [x] l10n_ch_base_bank #288 
- [ ] l10n_ch_credit_control_payment_slip_report
- [ ] l10n_ch_dta
- [x] l10n_ch_fds_postfinance @ecino #409
- [x] l10n_ch_fds_upload_dd @ecino #409
- [x] l10n_ch_fds_upload_sepa @ecino #409
- [ ] l10n_ch_hr_payroll
- [x] l10n_ch_import_cresus @grindtildeath #348 
- [x] l10n_ch_import_winbiz @lbeopennet #349
- [x] l10n_ch_lsv_dd #362 @ecino 
- [x] l10n_ch_pain_base https://github.com/OCA/l10n-switzerland/pull/306 @leemannd
- [x] l10n_ch_pain_credit_transfer https://github.com/OCA/l10n-switzerland/pull/307 @leemannd
- [ ] l10n_ch_pain_direct_debit
- [x] l10n_ch_payment_slip @grindtildeath https://github.com/OCA/l10n-switzerland/pull/295
- [ ] l10n_ch_payment_slip_account_statement_base_completion
- [ ] l10n_ch_payment_slip_layouts
- [x] l10n_ch_scan_bvr - @BT-aestebanez #337 
- [x] l10n_ch_states #293
- [x] l10n_ch_zip #292

**Comment by leemannd** [comment]
Porting l10n_ch_pain_base https://github.com/OCA/l10n-switzerland/pull/306
& l10n_ch_pain_credit_transfer https://github.com/OCA/l10n-switzerland/pull/307

**Comment by BT-aestebanez** [comment]
Hi, I would like to migrate l10n_ch_scan_bvr to 10.0 (as I already did with 8.0 -> 9.0)
However, current version of the module uses the old API, in other words, it was created from v8.0 (or older).
So, I think we should firstly cherry pick this PR:
https://github.com/OCA/l10n-switzerland/pull/272
To avoid a huge amount of changes

I could do it myself if needed.

Regards
Alvaro

**Comment by yvaucher** [comment]
@BT-aestebanez Yes you will need to cherry-pick the last changes from 9.0 branch.
I added you in the list.

**Comment by BT-aestebanez** [comment]
Porting l10n_ch_scan_bvr: https://github.com/OCA/l10n-switzerland/pull/337

**Comment by ecino** [comment]
Hi, when I try migrating a base in version 10, the module l10n_ch_bank calls migration script of version 9 which fails, because migration folder is 9.0.9.0. Shouldn't it be 9.0.1.0 instead ?
https://github.com/OCA/l10n-switzerland/tree/10.0/l10n_ch_bank/migrations/9.0.9.0.0

**Comment by yvaucher** [comment]
This script was meant to migrate from 8.0 to 9.0.

And yes it is for 9.0.1.0.0. But as far as I know such migration script is there to upgrade from a 9.0.x to 9.0.y. I put this here to help migrations. For a completely operable script it should probably be added to OpenUpgrade project.

You can make the SQL request by hand to follow the xmlids.

**Comment by BT-aestebanez** [comment]
l10n_ch_scan_bvr is already migrated to 10.0, please update the list

**Comment by yvaucher** [comment]
done
