### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-switzerland#355]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] l10n_ch_bank @yvaucher https://github.com/OCA/l10n-switzerland/pull/367
- [ ] l10n_ch_bank_statement_import_postfinance @eicher31 #500
- [x] l10n_ch_base_bank @yvaucher https://github.com/OCA/l10n-switzerland/pull/367
- [ ] l10n_ch_credit_control_payment_slip_report
- [ ] ~l10n_ch_dta~ obsolete
- [ ] l10n_ch_fds_postfinance @open-net-sarl https://github.com/OCA/l10n-switzerland/pull/444
- [ ] l10n_ch_fds_upload_dd
- [ ] l10n_ch_fds_upload_sepa
- [x] l10n_ch_hr_payroll @antonioburic https://github.com/OCA/l10n-switzerland/pull/442
- [ ] l10n_ch_hr_payroll_report @antonioburic https://github.com/OCA/l10n-switzerland/pull/443
- [ ] l10n_ch_import_cresus
- [ ] l10n_ch_import_winbiz @asaunier #455
- [x] l10n_ch_pain_base @mpanarin #384  
- [x] l10n_ch_pain_credit_transfer @mpanarin #386 
- [ ] l10n_ch_pain_direct_debit @ecino #536 
- [x] l10n_ch_payment_slip @yvaucher #373 
- [ ] l10n_ch_payment_slip_account_statement_base_completion
- [ ] l10n_ch_payment_slip_layouts
- [x] l10n_ch_scan_bvr @MaxyMoos https://github.com/OCA/l10n-switzerland/pull/430
- [x] l10n_ch_states @yvaucher https://github.com/OCA/l10n-switzerland/pull/367
- [x] l10n_ch_zip @yvaucher https://github.com/OCA/l10n-switzerland/pull/367

**Comment by yvaucher** [comment]
As l10n_ch_bank l10n_ch_base_bank l10n_ch_zip l10n_ch_dta and l10n_ch_states have been created when splitting module l10n_ch I will rewrite history to keep trace of this.

**Comment by MaxyMoos** [comment]
Hi everyone,

Not sure this is the best place to post this, feel free to redirect me if there's a more relevant thread.

I'm currently working on porting `l10n_ch_scan_bvr`, but this ported module makes use of the field `isr_adherent_num` from the model `res.partner.bank`, which is declared in the module `l10n_ch_base_bank` but is **not** added to the default form view in this module.
According to the code comments, the addition of `isr_adherent_num` to the form view used to be done in the module `l10n_ch_payment_slip` ... which has been deactivated in v11 due to some ISR features being implemented in core Odoo.

My small question is: should I add this field to the res.partner.bank form view in `l10n_ch_scan_bvr` or should it be added directly in `l10n_ch_base_bank` ? The latter seems better to me but maybe there's a specific reason why it was not done then.

**Comment by yvaucher** [comment]
Hello @MaxyMoos ,

With the removal of `l10n_ch_payment_slip` we can add it in the view of `l10n_ch_base_bank`. While it would be of no use without `l10n_ch_scan_bvr` it would be a mess if each module added it the view.

Nevertheless, something can be done to hide it by default and show it if `l10n_ch_scan_bvr` or any other module using it is installed. It would be to add a security group on it in the view. And in xml data of `l10n_ch_scan_bvr` you would add the group to `base.group_user`.

That way the field would be visible only if you installed `l10n_ch_scan_bvr` or any other module that require this field.

**Comment by antonioburic** [comment]
Hi everyone,

@lucode and myself (CoobyTec) will be porting `l10n_ch_hr_payroll` and `l10n_ch_hr_payroll_report` to v11.

**Comment by asaunier** [comment]
Hi all
I have just created a PR aiming to migrate ``l10n_ch_import_winbiz``. See https://github.com/OCA/l10n-switzerland/pull/455

**Comment by yvaucher** [comment]
@asaunier Thanks, I added it to the list

**Comment by ecino** [comment]
import_postfinance module, which adds reading the .tar.gz archives and pictures of payment slips is migrated with this PR: https://github.com/OCA/l10n-switzerland/pull/500

**Comment by ecino** [comment]
l10n_ch_pain_direct_debit is here : https://github.com/OCA/l10n-switzerland/pull/536
