### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-switzerland#678]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] ~~ebill_paynet~~ obsolete
- [ ] ~~ebill_paynet_customer_free_ref~~ obsolete
- [x] l10n_ch_account_tags - By @simoneversienti - #712
- [ ] ~~l10n_ch_base_bank~~ obsolete
- [ ]  l10n_ch_bank - was necessary to have BIC info from banks, BIC is not mandatory anymore
- [ ] l10n_ch_invoice_reports (ISR report to be removed)
- [ ] ~~l10n_ch_isrb~~ obsolete
- [ ] l10n_ch_pain_base - By @BT-anieto - #725
- [ ] l10n_ch_pain_credit_transfer - By @BT-anieto - #726
- [ ] l10n_ch_qr_bill_scan - By @sonhd91 - #698
- [ ]  ~~l10n_ch_states~~ Switzerland states included in base module
- [ ] ~~server_env_ebill_paynet~~ obsolete

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by sonhd91** [comment]
`l10n_ch_invoice_reports`: wip

**Comment by ivantodorovich** [comment]
- https://github.com/OCA/l10n-switzerland/pull/686
- https://github.com/OCA/l10n-switzerland/pull/687

**Comment by yvaucher** [comment]
@sonhd91 l10n_ch_invoice_reports is obsolete as the ISR report is not needed anymore.

**Comment by sonhd91** [comment]
`l10n_ch_qr_bill_scan`: https://github.com/OCA/l10n-switzerland/pull/698

**Comment by simoneversienti** [comment]
`l10n_ch_account_tags`: https://github.com/OCA/l10n-switzerland/pull/712

**Comment by simoneversienti** [comment]
> `l10n_ch_account_tags`: #712

@yvaucher can you update the section "Modules to migrate"? My PR is for `l10n_ch_account_tags`

**Comment by BT-anieto** [comment]
l10n_ch_pain_base #725 
l10n_ch_pain_credit_transfer #726
